### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by aerni** [riasvdv/statamic-button-box#2]
I'd love to use this but it doesn't really work at all. The fieldtype seems broken. I get tons of errors in the console when editing the fieldtype:
<img width="840" alt="Screenshot 2021-03-03 at 6 43 30 PM" src="https://user-images.githubusercontent.com/23167701/109848274-5b8b0f00-7c50-11eb-9101-1d27c8981944.png">

And using it doesn't work either. It doesn't show any icon nor image:
<img width="2376" alt="Screenshot 2021-03-03 at 6 42 57 PM" src="https://user-images.githubusercontent.com/23167701/109848199-47dfa880-7c50-11eb-9b87-7f4c3a5c7999.png">

## System Details
Statamic 3.0.45 Pro
Laravel 8.30.1
PHP 7.4.15
aerni/dynamic-cache 1.0.0
aerni/social-links 2.2.0
aerni/zipper 1.2.0
aryehraber/statamic-font-awesome 2.0.0
aryehraber/statamic-impersonator 2.1.0
jonassiewertsen/statamic-livewire 2.4.0
rias/statamic-button-box 2.0.2
spatie/statamic-responsive-images 2.5.0
visuellverstehen/statamic-classify 2.0.1
withcandour/aardvark-seo 2.0.9

**Comment by riasvdv** [comment]
Hmm I’m using it on a couple sites, I’ll try and take a look soon what’s causing this

**Comment by aerni** [comment]
That’s odd. Maybe worth mentioning that I’m using the fieldtype in a Fieldset that is imported in a Replicator set.

**Comment by riasvdv** [comment]
So editing the fieldtype doesn't work quite right in the interface, that's a long standing open issue I've created: https://github.com/statamic/cms/issues/1616 (it should work if you click the "Add button", close the fieldtype and then reopen it, the extra fields should show up then.

As for the buttons not loading, I've recreated your setup and I'm having no issues:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/3626559/111067640-7ddd2200-84c5-11eb-9a8c-5656742c8765.png">

Are you getting any errors or indications that Fontawesome isn't loading?

**Comment by riasvdv** [comment]
I've added a new release which should fix the font loading
