### ISSUE TITLE
Cannot find module './button_box.svg'

### ISSUE THREAD

**Issue by aerni** [riasvdv/statamic-button-box#3]
I'm running into the following error when trying to add a Button Box field to my fieldset. I'm on `v2.0.3` and `Statamic v3.0.48`.

<img width="1567" alt="Screenshot 2021-03-23 at 10 13 20 AM" src="https://user-images.githubusercontent.com/23167701/112122277-66d2ba00-8bc0-11eb-897c-630e4b77ae9c.png">

**Comment by riasvdv** [comment]
That's just because there's no icon set, it should still work though.

**Comment by GertTimmerman** [comment]
I have the same error. When i want to add the button box, i only see a never ending loading indicator, so it is not working right now. How can I set an icon?
