### ISSUE TITLE
Error 500 endless loading

### ISSUE THREAD

**Issue by wm-simon** [riasvdv/statamic-button-box#4]
Hey, I want to use your addon. When I try to add the field, it's loading endless.

![image](https://user-images.githubusercontent.com/3351449/149338711-8443be62-3a8e-457e-9394-c19cba83570d.png)

**Comment by riasvdv** [comment]
I can't seem to replicate this, could you check your laravel.log (in storage/logs) to see which exception you get?

**Comment by wm-simon** [comment]
#5 solved this problem too.
