### ISSUE TITLE
Button box doesn't seem to work when adding a new button

### ISSUE THREAD

**Issue by ItsRD** [riasvdv/statamic-button-box#6]
Whenever I try to add a new button to the options I get an error saying "TypeError: Cannot read properties of undefined (reading 'label')".

I think it might be an issue because of the newest Statamic version, but I'm not sure. I've tested on a clean Statamic project and get the same error.

Any idea how to fix this?

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/4502205/180965460-5c8d2fde-38a8-4a8d-880a-5bae68533d1d.png">

<img width="499" alt="image" src="https://user-images.githubusercontent.com/4502205/180965911-0993bc60-03c1-4401-a73d-81a308aadd69.png">

**Comment by riasvdv** [comment]
Unfortunately this is a Statamic issue: https://github.com/statamic/cms/issues/1616

For now I suggest adding all the options using the yaml file, after which you can update them through the interface, adding/removing is an issue

**Comment by ItsRD** [comment]
Aaah okay, thanks!
