### ISSUE TITLE
Statamic V4 support

### ISSUE THREAD

**Issue by quintenbuis** [riasvdv/statamic-button-box#7]
The current state is incompatible with V4.

* It cannot be installed due to composer.json restrictions.
* When allowing v4 in composer.json the buttons don't work anymore.

**Comment by pdipatrizio** [comment]
Out of the handful of addons I'm using, Button Box is the only one still without a v4 update. I expected more from a paid addon, to be frank.

**Comment by riasvdv** [comment]
I am currently on honeymoon. I’ll pick this up as soon as I get back

**Comment by quintenbuis** [comment]
@riasvdv Do you have an ETA on the V4 support?

**Comment by riasvdv** [comment]
v3 of this addon has support for Statamic v4 now!
