### ISSUE TITLE
Images not rendering

### ISSUE THREAD

**Issue by quintenbuis** [riasvdv/statamic-button-box#8]
When using images to represent the buttons it doesn't render and only shows a dot.
![image](https://github.com/riasvdv/statamic-button-box/assets/36452184/1a52f815-234b-4923-9772-2bb74a7588aa)

The network tab gives the following 404's:
![image](https://github.com/riasvdv/statamic-button-box/assets/36452184/d56843c3-e3d3-46a6-9d16-04298f7f4ac0)

**Comment by riasvdv** [comment]
Should be fixed in v3.0.1! Thanks for reporting this

**Comment by quintenbuis** [comment]
I'm curious.  @riasvdv Where did you find how to fix the bug? I've been struggling to find good documentation / examples on Statamic addons.

**Comment by riasvdv** [comment]
I looked at Statamic's own AssetFieldType as an example, seems like they switched to a POST request instead of a GET request for the asset info

**Comment by quintenbuis** [comment]
Ahh thanks. Code diving it is. Thanks for the quick bug fix and quick response 🚀 💯
